apiVersion: v1
kind: Namespace
metadata:
  name: backend-prd

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend-prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: escolhas/personal-repository:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend-prd
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: backend
