version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/repo
    environment:
      DOCKER_TLS_CERTDIR: "/certs"

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t backend-app:latest -f deploy/Dockerfile .

  deploy:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Login to Argo CD
          command: |
            argocd login $ARGOCD_HOST --username admin --password $ARGOCD_PASSWORD
      - run:
          name: Deploy to Kubernetes
          command: |
            kubectl apply -f kubernetes/prd/deployment.yaml

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
